### ISSUE TITLE
Please publish esm + cjs similar to react-advanced-cropper

### ISSUE THREAD

**Issue by sushantdhiman** [advanced-cropper/advanced-cropper#1]
With the recent release, it is suggested in [recipes](https://advanced-cropper.github.io/react-advanced-cropper/docs/guides/recipes#load-image-from-a-disc) to directly import `getMimeType` method from this library.

But this library is published only in `esm` module type i.e. using `import` statement in published code. I suggest publishing in esm and cjs modes, similar to `react-advanced-cropper`.

Alternatively, I propose reverting to the previous behaviour of `react-advanced-cropper`, i.e. we should not need to add `advanced-cropper` directly to our project because it is already used by `react-advanced-cropper`. Helper methods should be exported by `react-advanced-cropper` directly.

**Comment by Norserium** [comment]
@sushantdhiman, thank you for your feedback.

It was a hard decision. I can't export all extensions in `react-advanced-cropper` because it will lead to a huge bundle with the content that need only a small minority of users, so it should be externalize somehow.

I will try to figure out how to it in a convenient way. By the way, why do you use `cjs` modules?

**Comment by Norserium** [comment]
@sushantdhiman, try to update `react-advanced-cropper` to `0.10.1`.

**Comment by sushantdhiman** [comment]
@Norserium Thanks, new published release works with common-js setup.

> By the way, why do you use cjs modules?

1. ESM implementation is not mature enough. Especially when used with Typescript. There are many bugs, like the need to specify the extension name in imports etc.
2. Many mainstream modules, such as https://github.com/firebase/firebaseui-web-react/blob/49f80b5d1548e4d4a2575e0e7f998e7148440405, still use require.

I think I can only move to `esm` when it starts working correctly out-of-the-box.

**Comment by Norserium** [comment]
@sushantdhiman, that's great.

> ESM implementation is not mature enough. Especially when used with Typescript. There are many bugs, like the need to specify the extension name in imports etc.

I didn't encounter this bugs (it is worth mentioning, that I use rollup / webpack). I will take into account this points.
